// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using System;
    using UnityEngine;

    public struct _8c7692f3e8b1b43b29b6c99cbeebfcb4 : IEntityInput, IEquatable<_8c7692f3e8b1b43b29b6c99cbeebfcb4>
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector2 Movement;
        }

        public static unsafe _8c7692f3e8b1b43b29b6c99cbeebfcb4 FromInterop(System.IntPtr data, System.Int32 dataSize)
        {
            if (dataSize != 8) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 8) " +
                    "for input with ID 0");
            }

            var orig = new _8c7692f3e8b1b43b29b6c99cbeebfcb4();
            var comp = (Interop*)data;
            orig.Movement = comp->Movement;
            return orig;
        }

        public uint GetComponentType() => 0;

        public Entity Entity { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public long Frame { get; set; }
        private bool isRemoteInput;

        public Vector2 Movement;

        public _8c7692f3e8b1b43b29b6c99cbeebfcb4(
        Entity entity,
        long frame,
        Vector2 Movement,
        bool isRemoteInput)
        {
            this.Entity = entity;
            this.Routing = MessageTarget.All;
            this.Sender = 0;
            this.Frame = frame;
            this.isRemoteInput = isRemoteInput;
            this.Movement = Movement;
        }

        public override string ToString()
        {
            return $"Entity: {Entity}, Frame: {Frame}, Inputs: [Movement:{Movement}]";
        }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }

        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() => default;

        public void NullEntityRefs(Entity entity) { }

        public bool Equals(_8c7692f3e8b1b43b29b6c99cbeebfcb4 other)
        {
            return
                this.Movement == other.Movement;
        }

        public static void Serialize(_8c7692f3e8b1b43b29b6c99cbeebfcb4 inputData, IOutProtocolBitStream bitStream)
        {
            var converted_Movement = inputData.Movement.ToCoreVector2();
            bitStream.WriteVector2(converted_Movement, FloatMeta.NoCompression());
        }

        public static _8c7692f3e8b1b43b29b6c99cbeebfcb4 Deserialize(IInProtocolBitStream bitStream, Entity entity, long frame)
        {
            var converted_Movement = bitStream.ReadVector2(FloatMeta.NoCompression());
            var dataMovement = converted_Movement.ToUnityVector2();

            return new _8c7692f3e8b1b43b29b6c99cbeebfcb4()
            {
                Entity = entity,
                Frame = frame,
                Movement = dataMovement,
                isRemoteInput = true
            };
        }
    }


}