// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;

    public struct _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Single MoveSpeed;
            [FieldOffset(4)]
            public System.Byte Grounded;
            [FieldOffset(5)]
            public System.Byte CarryingBig;
            [FieldOffset(6)]
            public System.Byte CarryingSmall;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.MoveSpeedMask;
            MoveSpeedSimulationFrame = frame;
            FieldsMask |= _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.GroundedMask;
            GroundedSimulationFrame = frame;
            FieldsMask |= _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.CarryingBigMask;
            CarryingBigSimulationFrame = frame;
            FieldsMask |= _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.CarryingSmallMask;
            CarryingSmallSimulationFrame = frame;
        }

        public static unsafe _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 7) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 7) " +
                    "for component with ID 171");
            }

            if (simFramesCount != 4) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 4) " +
                    "for component with ID 171");
            }

            var orig = new _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941();

            var comp = (Interop*)data;

            orig.MoveSpeed = comp->MoveSpeed;
            orig.MoveSpeedSimulationFrame = simFrames[0].Into();
            orig.Grounded = comp->Grounded != 0;
            orig.GroundedSimulationFrame = simFrames[1].Into();
            orig.CarryingBig = comp->CarryingBig != 0;
            orig.CarryingBigSimulationFrame = simFrames[2].Into();
            orig.CarryingSmall = comp->CarryingSmall != 0;
            orig.CarryingSmallSimulationFrame = simFrames[3].Into();

            return orig;
        }

        public static unsafe _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941 FromInteropArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941_LOD0(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 7) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 7) " +
                    "for component with ID 203");
            }

                
            if (simFramesCount != 4) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 4) " +
                    "for component with ID 203");
            }

            var orig = new _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941();

            var comp = (Interop*)data;

            orig.MoveSpeed = comp->MoveSpeed;
            orig.MoveSpeedSimulationFrame = simFrames[0].Into();
            orig.Grounded = comp->Grounded != 0;
            orig.GroundedSimulationFrame = simFrames[1].Into();
            orig.CarryingBig = comp->CarryingBig != 0;
            orig.CarryingBigSimulationFrame = simFrames[2].Into();
            orig.CarryingSmall = comp->CarryingSmall != 0;
            orig.CarryingSmallSimulationFrame = simFrames[3].Into();

            return orig;
        }

        public static uint MoveSpeedMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame MoveSpeedSimulationFrame;
        public System.Single MoveSpeed;
        public static uint GroundedMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame GroundedSimulationFrame;
        public System.Boolean Grounded;
        public static uint CarryingBigMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame CarryingBigSimulationFrame;
        public System.Boolean CarryingBig;
        public static uint CarryingSmallMask => 0b00000000000000000000000000001000;
        public AbsoluteSimulationFrame CarryingSmallSimulationFrame;
        public System.Boolean CarryingSmall;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 171;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000001111;
        public bool HasFields() => true;
        public bool HasRefFields() => false;

        private long[] simulationFrames;

        public long[] GetSimulationFrames() {
            if (simulationFrames == null)
            {
                simulationFrames = new long[4];
            }

            simulationFrames[0] = MoveSpeedSimulationFrame;
            simulationFrames[1] = GroundedSimulationFrame;
            simulationFrames[2] = CarryingBigSimulationFrame;
            simulationFrames[3] = CarryingSmallSimulationFrame;

            return simulationFrames;
        }

        public int GetFieldCount() => 4;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;

        private static readonly float _MoveSpeed_Min = 0f;
        private static readonly float _MoveSpeed_Max = 10f;

        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;

            if ((FieldsMask & _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.MoveSpeedMask) != 0 && (min == null || this.MoveSpeedSimulationFrame < min))
            {
                min = this.MoveSpeedSimulationFrame;
            }
            if ((FieldsMask & _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.GroundedMask) != 0 && (min == null || this.GroundedSimulationFrame < min))
            {
                min = this.GroundedSimulationFrame;
            }
            if ((FieldsMask & _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.CarryingBigMask) != 0 && (min == null || this.CarryingBigSimulationFrame < min))
            {
                min = this.CarryingBigSimulationFrame;
            }
            if ((FieldsMask & _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.CarryingSmallMask) != 0 && (min == null || this.CarryingSmallSimulationFrame < min))
            {
                min = this.CarryingSmallSimulationFrame;
            }

            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.MoveSpeedSimulationFrame = other.MoveSpeedSimulationFrame;
                this.MoveSpeed = other.MoveSpeed;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.GroundedSimulationFrame = other.GroundedSimulationFrame;
                this.Grounded = other.Grounded;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.CarryingBigSimulationFrame = other.CarryingBigSimulationFrame;
                this.CarryingBig = other.CarryingBig;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.CarryingSmallSimulationFrame = other.CarryingSmallSimulationFrame;
                this.CarryingSmall = other.CarryingSmall;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 4);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                if (isRefSimFrameValid) {
                    var simFrameDelta = data.MoveSpeedSimulationFrame - referenceSimulationFrame;
                    if (simFrameDelta > byte.MaxValue) {
                        simFrameDelta = byte.MaxValue;
                    }

                    SerializeTools.WriteFieldSimFrameDelta(bitStream, (byte)simFrameDelta);
                } else {
                    SerializeTools.WriteFieldSimFrameDelta(bitStream, 0);
                }

                Coherence.Utils.Bounds.Check(data.MoveSpeed, _MoveSpeed_Min, _MoveSpeed_Max, "_cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.MoveSpeed", logger);


                var fieldValue = data.MoveSpeed;



                bitStream.WriteFloat(fieldValue, FloatMeta.ForFixedPoint(0, 10, 0.001d));
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                if (isRefSimFrameValid) {
                    var simFrameDelta = data.GroundedSimulationFrame - referenceSimulationFrame;
                    if (simFrameDelta > byte.MaxValue) {
                        simFrameDelta = byte.MaxValue;
                    }

                    SerializeTools.WriteFieldSimFrameDelta(bitStream, (byte)simFrameDelta);
                } else {
                    SerializeTools.WriteFieldSimFrameDelta(bitStream, 0);
                }


                var fieldValue = data.Grounded;



                bitStream.WriteBool(fieldValue);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                if (isRefSimFrameValid) {
                    var simFrameDelta = data.CarryingBigSimulationFrame - referenceSimulationFrame;
                    if (simFrameDelta > byte.MaxValue) {
                        simFrameDelta = byte.MaxValue;
                    }

                    SerializeTools.WriteFieldSimFrameDelta(bitStream, (byte)simFrameDelta);
                } else {
                    SerializeTools.WriteFieldSimFrameDelta(bitStream, 0);
                }


                var fieldValue = data.CarryingBig;



                bitStream.WriteBool(fieldValue);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                if (isRefSimFrameValid) {
                    var simFrameDelta = data.CarryingSmallSimulationFrame - referenceSimulationFrame;
                    if (simFrameDelta > byte.MaxValue) {
                        simFrameDelta = byte.MaxValue;
                    }

                    SerializeTools.WriteFieldSimFrameDelta(bitStream, (byte)simFrameDelta);
                } else {
                    SerializeTools.WriteFieldSimFrameDelta(bitStream, 0);
                }


                var fieldValue = data.CarryingSmall;



                bitStream.WriteBool(fieldValue);
            }

            mask >>= 1;

            return mask;
        }

        public static _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(4);
            }

            var val = new _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941();
            if (bitStream.ReadMask())
            {
                val.MoveSpeedSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.MoveSpeed = bitStream.ReadFloat(FloatMeta.ForFixedPoint(0, 10, 0.001d));
                val.FieldsMask |= _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.MoveSpeedMask;
            }
            if (bitStream.ReadMask())
            {
                val.GroundedSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.Grounded = bitStream.ReadBool();
                val.FieldsMask |= _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.GroundedMask;
            }
            if (bitStream.ReadMask())
            {
                val.CarryingBigSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.CarryingBig = bitStream.ReadBool();
                val.FieldsMask |= _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.CarryingBigMask;
            }
            if (bitStream.ReadMask())
            {
                val.CarryingSmallSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.CarryingSmall = bitStream.ReadBool();
                val.FieldsMask |= _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.CarryingSmallMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }

        public static _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941 DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941_LOD0(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(4);
            }

            var val = new _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941();
            if (bitStream.ReadMask())
            {
                val.MoveSpeedSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.MoveSpeed = bitStream.ReadFloat(FloatMeta.ForFixedPoint(0, 10, 0.001d));
                val.FieldsMask |= MoveSpeedMask;
            }
            if (bitStream.ReadMask())
            {
                val.GroundedSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.Grounded = bitStream.ReadBool();
                val.FieldsMask |= GroundedMask;
            }
            if (bitStream.ReadMask())
            {
                val.CarryingBigSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.CarryingBig = bitStream.ReadBool();
                val.FieldsMask |= CarryingBigMask;
            }
            if (bitStream.ReadMask())
            {
                val.CarryingSmallSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.CarryingSmall = bitStream.ReadBool();
                val.FieldsMask |= CarryingSmallMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }

        public override string ToString()
        {
            return $"_cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941(" +
                $" MoveSpeed: { this.MoveSpeed }" +
                $", MoveSpeedSimFrame: { this.MoveSpeedSimulationFrame }" +
                $" Grounded: { this.Grounded }" +
                $", GroundedSimFrame: { this.GroundedSimulationFrame }" +
                $" CarryingBig: { this.CarryingBig }" +
                $", CarryingBigSimFrame: { this.CarryingBigSimulationFrame }" +
                $" CarryingSmall: { this.CarryingSmall }" +
                $", CarryingSmallSimFrame: { this.CarryingSmallSimulationFrame }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(4, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(4, '0') })";
        }
    }


}