// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;

    public struct Connection : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.UInt32 id;
            [FieldOffset(4)]
            public System.Int32 type;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= Connection.idMask;
            idSimulationFrame = frame;
            FieldsMask |= Connection.typeMask;
            typeSimulationFrame = frame;
        }

        public static unsafe Connection FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 8) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 8) " +
                    "for component with ID 8");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 8");
            }

            var orig = new Connection();

            var comp = (Interop*)data;

            orig.id = comp->id;
            orig.type = comp->type;

            return orig;
        }


        public static uint idMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame idSimulationFrame;
        public System.UInt32 id;
        public static uint typeMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame typeSimulationFrame;
        public System.Int32 type;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 8;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000011;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 2;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;

        private static readonly System.UInt32 _id_Min = 0;
        private static readonly System.UInt32 _id_Max = 2147483647;
        private static readonly System.Int32 _type_Min = 0;
        private static readonly System.Int32 _type_Max = 8;

        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (Connection)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.idSimulationFrame = other.idSimulationFrame;
                this.id = other.id;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.typeSimulationFrame = other.typeSimulationFrame;
                this.type = other.type;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(Connection data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 2);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {

                Coherence.Utils.Bounds.Check(data.id, _id_Min, _id_Max, "Connection.id", logger);

                data.id = Coherence.Utils.Bounds.Clamp(data.id, _id_Min, _id_Max);

                var fieldValue = data.id;



                bitStream.WriteUIntegerRange(fieldValue, 31, 0);
            }

            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {

                Coherence.Utils.Bounds.Check(data.type, _type_Min, _type_Max, "Connection.type", logger);

                data.type = Coherence.Utils.Bounds.Clamp(data.type, _type_Min, _type_Max);

                var fieldValue = data.type;



                bitStream.WriteIntegerRange(fieldValue, 3, 0);
            }

            mask >>= 1;

            return mask;
        }

        public static Connection Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(2);
            }

            var val = new Connection();
            if (bitStream.ReadMask())
            {

                val.id = bitStream.ReadUIntegerRange(31, 0);
                val.FieldsMask |= Connection.idMask;
            }
            if (bitStream.ReadMask())
            {

                val.type = bitStream.ReadIntegerRange(3, 0);
                val.FieldsMask |= Connection.typeMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"Connection(" +
                $" id: { this.id }" +
                $" type: { this.type }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(2, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(2, '0') })";
        }
    }

}
