// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct QuerySynced : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Byte liveQuerySynced;
            [FieldOffset(1)]
            public System.Byte globalQuerySynced;
        }

        public static unsafe QuerySynced FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 2) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 2) " +
                    "for command with ID 2");
            }

            var orig = new QuerySynced();
            var comp = (Interop*)data;
            orig.liveQuerySynced = comp->liveQuerySynced != 0;
            orig.globalQuerySynced = comp->globalQuerySynced != 0;
            return orig;
        }

        public System.Boolean liveQuerySynced;
        public System.Boolean globalQuerySynced;
        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Target { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        public uint GetComponentType() => 2;
        public bool UsesMeta { get; set; }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        public QuerySynced(
            Entity entity,
            System.Boolean liveQuerySynced,
            System.Boolean globalQuerySynced
        )
        {
            Entity = entity;
            ChannelID = Coherence.ChannelID.Default;
            Target = default;
            Routing = MessageTarget.All;
            SenderParticipant = 0;
            SenderClientID = default;
            Frame = 0;
            UsesMeta = false;

            this.liveQuerySynced = liveQuerySynced; 
            this.globalQuerySynced = globalQuerySynced; 
        }
        
        public static void Serialize(QuerySynced commandData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteBool(commandData.liveQuerySynced);
            bitStream.WriteBool(commandData.globalQuerySynced);
        }
        
        public static QuerySynced Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
            var dataliveQuerySynced = bitStream.ReadBool();
            var dataglobalQuerySynced = bitStream.ReadBool();
    
            return new QuerySynced()
            {
                Entity = entity,
                Routing = target,
                Target = target,
                liveQuerySynced = dataliveQuerySynced,
                globalQuerySynced = dataglobalQuerySynced
            };   
        }
    }

}
