// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    
    public struct AssetId : ICoherenceComponentData
    {
        public static uint valueMask => 0b00000000000000000000000000000001;
        public System.String value;
        public static uint isFromGroupMask => 0b00000000000000000000000000000010;
        public System.Boolean isFromGroup;
        
        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 16;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000011;
        public bool HasFields() => true;
        public bool HasRefFields() => false;
        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;  
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;   
        }
        
        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;
        public AbsoluteSimulationFrame Frame;
        
    
        public void SetSimulationFrame(AbsoluteSimulationFrame frame)
        {
            Frame = frame;
        }
        
        public AbsoluteSimulationFrame GetSimulationFrame() => Frame;
        
        public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
        {
            var other = (AssetId)data;

            FieldsMask |= mask;
            StoppedMask &= ~(mask);

            if ((mask & 0x01) != 0)
            {
                Frame = other.Frame;
                value = other.value;
            }
            
            mask >>= 1;
            if ((mask & 0x01) != 0)
            {
                Frame = other.Frame;
                isFromGroup = other.isFromGroup;
            }
            
            mask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }
        
        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }
        
        public static uint Serialize(AssetId data, uint mask, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 2);
            }

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
            
                var fieldValue = data.value;
            

            
                bitStream.WriteShortString(fieldValue);
            }
            
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
            
                var fieldValue = data.isFromGroup;
            

            
                bitStream.WriteBool(fieldValue);
            }
            
            mask >>= 1;
          
            return mask;
        }
        
        public static (AssetId, uint) Deserialize(InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(2);
            }

            var mask = (uint)0;
            var val = new AssetId();
            if (bitStream.ReadMask())
            {
                val.value = bitStream.ReadShortString();
                mask |= valueMask;
            }
            if (bitStream.ReadMask())
            {
                val.isFromGroup = bitStream.ReadBool();
                mask |= isFromGroupMask;
            }
                    
            val.FieldsMask = mask;
            val.StoppedMask = stoppedMask;

            return (val, mask);
        }
        
        
        public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
        {
            var last = lastSent as AssetId?;
            
        }

        public override string ToString()
        {
            return $"AssetId(value: { value }, isFromGroup: { isFromGroup }, Mask: {System.Convert.ToString(FieldsMask, 2).PadLeft(2, '0')}), Stopped: {System.Convert.ToString(StoppedMask, 2).PadLeft(2, '0')})";
        }
    }
    

}