// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

namespace Coherence.Generated
{
    using UnityEngine;
    using Coherence.Toolkit;

    [UnityEngine.Scripting.Preserve]
    public class BakeInfo 
    {
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void OnRuntimeMethodLoad()
        {
            Impl.BakedDataSchemaID = "61d540f2f1702355eb7269d05a31a4e09e430ab0";
        }
    }
}
