// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_4d9a6244_2a07_4534_bca0_27258cca3b8c : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			return update.value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_60b57dc1_05e3_4765_bb24_9dbf96b35ed4 : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(coherenceSync.coherenceRotation);
			set => coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldOrientation)coherenceComponent;
			return update.value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldOrientation)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_11b3179c_3374_4fba_a48c_8c52ce7a5719 : IntBinding
	{
		private CosmeticsChanger CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (CosmeticsChanger)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_CosmeticsChanger_5911091967807195199";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.currentHat);
			set => CastedUnityComponent.currentHat = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_CosmeticsChanger_5911091967807195199)coherenceComponent;
			return update.currentHat;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_CosmeticsChanger_5911091967807195199)coherenceComponent;
			update.currentHat = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_CosmeticsChanger_5911091967807195199();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_08c9688a_6c1b_43f0_a868_56f171ae2df2 : IntBinding
	{
		private CosmeticsChanger CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (CosmeticsChanger)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_CosmeticsChanger_5911091967807195199";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.currentHairStyle);
			set => CastedUnityComponent.currentHairStyle = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_CosmeticsChanger_5911091967807195199)coherenceComponent;
			return update.currentHairStyle;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_CosmeticsChanger_5911091967807195199)coherenceComponent;
			update.currentHairStyle = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_CosmeticsChanger_5911091967807195199();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_e388fa51_05b3_4f7a_836f_ca12ec0a7030 : IntBinding
	{
		private CosmeticsChanger CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (CosmeticsChanger)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_CosmeticsChanger_5911091967807195199";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.currentFacialHair);
			set => CastedUnityComponent.currentFacialHair = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_CosmeticsChanger_5911091967807195199)coherenceComponent;
			return update.currentFacialHair;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_CosmeticsChanger_5911091967807195199)coherenceComponent;
			update.currentFacialHair = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_CosmeticsChanger_5911091967807195199();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_35fe21b9_6141_49b4_8553_511c0683c2f9 : IntBinding
	{
		private CosmeticsChanger CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (CosmeticsChanger)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_CosmeticsChanger_5911091967807195199";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.currentBackpack);
			set => CastedUnityComponent.currentBackpack = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_CosmeticsChanger_5911091967807195199)coherenceComponent;
			return update.currentBackpack;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_CosmeticsChanger_5911091967807195199)coherenceComponent;
			update.currentBackpack = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_CosmeticsChanger_5911091967807195199();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_9730620f_6eb4_4d01_b04e_80e5fc5e4856 : IntBinding
	{
		private CosmeticsChanger CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (CosmeticsChanger)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_CosmeticsChanger_5911091967807195199";

		public override uint FieldMask => 0b00000000000000000000000000010000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.currentSkinTone);
			set => CastedUnityComponent.currentSkinTone = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_CosmeticsChanger_5911091967807195199)coherenceComponent;
			return update.currentSkinTone;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_CosmeticsChanger_5911091967807195199)coherenceComponent;
			update.currentSkinTone = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_CosmeticsChanger_5911091967807195199();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_2ffecec9_e60b_43ea_89f0_a6e4bd8598b3 : StringBinding
	{
		private TMPro.TextMeshProUGUI CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (TMPro.TextMeshProUGUI)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_TMPro__char_46_TextMeshProUGUI_2783100773886260066";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override string Value
		{
			get => (string)(System.String)(CastedUnityComponent.text);
			set => CastedUnityComponent.text = (System.String)(value);
		}

		protected override string ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_TMPro__char_46_TextMeshProUGUI_2783100773886260066)coherenceComponent;
			return update.text;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_TMPro__char_46_TextMeshProUGUI_2783100773886260066)coherenceComponent;
			update.text = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_TMPro__char_46_TextMeshProUGUI_2783100773886260066();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_2280fcb3_95a9_42a1_b93a_293e112d8673 : FloatAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Animator_8498588009909292941";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override float Value
		{
			get => (float)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, (value));
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_8498588009909292941)coherenceComponent;
			return update.MoveSpeed;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_8498588009909292941)coherenceComponent;
			update.MoveSpeed = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Animator_8498588009909292941();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_ac5c023b_1b54_4b7b_a9b7_ce8c808091cc : BoolAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Animator_8498588009909292941";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override bool Value
		{
			get => (bool)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, (value));
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_8498588009909292941)coherenceComponent;
			return update.Grounded;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_8498588009909292941)coherenceComponent;
			update.Grounded = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Animator_8498588009909292941();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_9be70ffe_5c84_4080_bcc6_320f8619ca6d : BoolAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Animator_8498588009909292941";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override bool Value
		{
			get => (bool)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, (value));
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_8498588009909292941)coherenceComponent;
			return update.CarryingBig;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_8498588009909292941)coherenceComponent;
			update.CarryingBig = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Animator_8498588009909292941();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_4ee471e8_90da_4553_ac85_52fed6078db5 : BoolAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Animator_8498588009909292941";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override bool Value
		{
			get => (bool)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, (value));
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_8498588009909292941)coherenceComponent;
			return update.CarryingSmall;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Animator_8498588009909292941)coherenceComponent;
			update.CarryingSmall = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Animator_8498588009909292941();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_792d6900_fc74_4c2f_9fb4_7b533b2dadd6 : DeepRotationBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Transform_4582869309862079177";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(CastedUnityComponent.localRotation);
			set => CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_4582869309862079177)coherenceComponent;
			return update.rotation;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_4582869309862079177)coherenceComponent;
			update.rotation = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Transform_4582869309862079177();
		}
	}

	public class Binding_cd9bcc1feead9419fac0c5981ce85c23_e1e87976_a62a_499c_9c88_381bbdde8ec3 : DeepPositionBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Transform_7791709351172572033";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localPosition);
			set => CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_7791709351172572033)coherenceComponent;
			return update.position;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_7791709351172572033)coherenceComponent;
			update.position = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Transform_7791709351172572033();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Player' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncPlayer_id0 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands		
		private UnityEngine.Animator Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8_CommandTarget;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncPlayer_id0>();
			if (coherenceSync.TryGetBindingByGuid("d210a4b9-ddf7-480f-9743-18bf1cd06aa8", "SetTrigger", out Binding Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8))
			{
				Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8_CommandTarget = (UnityEngine.Animator)Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("UnityEngine.Animator.SetTrigger", "(System.String)",
				SendCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8, ReceiveLocalCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8, MessageTarget.All, Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (SetTrigger)");
			}
			if (coherenceSync.TryGetBindingByGuid("4d9a6244-2a07-4534-bca0-27258cca3b8c", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_4d9a6244_2a07_4534_bca0_27258cca3b8c();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("60b57dc1-05e3-4765-bb24-9dbf96b35ed4", "rotation", out Binding InternalWorldOrientation_Rotation_value))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_60b57dc1_05e3_4765_bb24_9dbf96b35ed4();
				InternalWorldOrientation_Rotation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldOrientation_Rotation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("11b3179c-3374-4fba-a48c-8c52ce7a5719", "currentHat", out Binding InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentHat))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_11b3179c_3374_4fba_a48c_8c52ce7a5719();
				InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentHat.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentHat)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (CosmeticsChanger).currentHat");
			}
			if (coherenceSync.TryGetBindingByGuid("08c9688a-6c1b-43f0-a868-56f171ae2df2", "currentHairStyle", out Binding InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentHairStyle))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_08c9688a_6c1b_43f0_a868_56f171ae2df2();
				InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentHairStyle.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentHairStyle)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (CosmeticsChanger).currentHairStyle");
			}
			if (coherenceSync.TryGetBindingByGuid("e388fa51-05b3-4f7a-836f-ca12ec0a7030", "currentFacialHair", out Binding InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentFacialHair))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_e388fa51_05b3_4f7a_836f_ca12ec0a7030();
				InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentFacialHair.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentFacialHair)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (CosmeticsChanger).currentFacialHair");
			}
			if (coherenceSync.TryGetBindingByGuid("35fe21b9-6141-49b4-8553-511c0683c2f9", "currentBackpack", out Binding InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentBackpack))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_35fe21b9_6141_49b4_8553_511c0683c2f9();
				InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentBackpack.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentBackpack)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (CosmeticsChanger).currentBackpack");
			}
			if (coherenceSync.TryGetBindingByGuid("9730620f-6eb4-4d01-b04e-80e5fc5e4856", "currentSkinTone", out Binding InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentSkinTone))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_9730620f_6eb4_4d01_b04e_80e5fc5e4856();
				InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentSkinTone.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_CosmeticsChanger_5911091967807195199_Player_id0_CosmeticsChanger_5911091967807195199_currentSkinTone)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (CosmeticsChanger).currentSkinTone");
			}
			if (coherenceSync.TryGetBindingByGuid("2ffecec9-e60b-43ea-89f0-a6e4bd8598b3", "text", out Binding InternalPlayer_id0_TMPro__char_46_TextMeshProUGUI_2783100773886260066_Player_id0_TMPro__char_46_TextMeshProUGUI_2783100773886260066_text))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_2ffecec9_e60b_43ea_89f0_a6e4bd8598b3();
				InternalPlayer_id0_TMPro__char_46_TextMeshProUGUI_2783100773886260066_Player_id0_TMPro__char_46_TextMeshProUGUI_2783100773886260066_text.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_TMPro__char_46_TextMeshProUGUI_2783100773886260066_Player_id0_TMPro__char_46_TextMeshProUGUI_2783100773886260066_text)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (TMPro.TextMeshProUGUI).text");
			}
			if (coherenceSync.TryGetBindingByGuid("2280fcb3-95a9-42a1-b93a-293e112d8673", "MoveSpeed", out Binding InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_MoveSpeed))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_2280fcb3_95a9_42a1_b93a_293e112d8673();
				InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_MoveSpeed.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_MoveSpeed)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).MoveSpeed");
			}
			if (coherenceSync.TryGetBindingByGuid("ac5c023b-1b54-4b7b-a9b7-ce8c808091cc", "Grounded", out Binding InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_Grounded))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_ac5c023b_1b54_4b7b_a9b7_ce8c808091cc();
				InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_Grounded.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_Grounded)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).Grounded");
			}
			if (coherenceSync.TryGetBindingByGuid("9be70ffe-5c84-4080-bcc6-320f8619ca6d", "CarryingBig", out Binding InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_CarryingBig))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_9be70ffe_5c84_4080_bcc6_320f8619ca6d();
				InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_CarryingBig.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_CarryingBig)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).CarryingBig");
			}
			if (coherenceSync.TryGetBindingByGuid("4ee471e8-90da-4553-ac85-52fed6078db5", "CarryingSmall", out Binding InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_CarryingSmall))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_4ee471e8_90da_4553_ac85_52fed6078db5();
				InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_CarryingSmall.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Animator_8498588009909292941_Player_id0_UnityEngine__char_46_Animator_8498588009909292941_CarryingSmall)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).CarryingSmall");
			}
			if (coherenceSync.TryGetBindingByGuid("792d6900-fc74-4c2f-9fb4-7b533b2dadd6", "rotation", out Binding InternalPlayer_id0_UnityEngine__char_46_Transform_4582869309862079177_Player_id0_UnityEngine__char_46_Transform_4582869309862079177_rotation))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_792d6900_fc74_4c2f_9fb4_7b533b2dadd6();
				InternalPlayer_id0_UnityEngine__char_46_Transform_4582869309862079177_Player_id0_UnityEngine__char_46_Transform_4582869309862079177_rotation.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Transform_4582869309862079177_Player_id0_UnityEngine__char_46_Transform_4582869309862079177_rotation)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("e1e87976-a62a-499c-9c88-381bbdde8ec3", "position", out Binding InternalPlayer_id0_UnityEngine__char_46_Transform_7791709351172572033_Player_id0_UnityEngine__char_46_Transform_7791709351172572033_position))
			{
				var clone = new Binding_cd9bcc1feead9419fac0c5981ce85c23_e1e87976_a62a_499c_9c88_381bbdde8ec3();
				InternalPlayer_id0_UnityEngine__char_46_Transform_7791709351172572033_Player_id0_UnityEngine__char_46_Transform_7791709351172572033_position.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Transform_7791709351172572033_Player_id0_UnityEngine__char_46_Transform_7791709351172572033_position)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}
		void SendCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8(MessageTarget target, object[] args)
		{
			var command = new Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8();
			int i = 0;
			command.name = (string)((System.String)args[i++]);
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8(MessageTarget target, object[] args)
		{
			var command = new Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8();
			int i = 0;
			command.name = (string)((System.String)args[i++]);
			ReceiveCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8(command);
		}

		void ReceiveCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8(Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8 command)
		{
			var target = Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8_CommandTarget;
			target.SetTrigger((System.String)(command.name));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8 castedCommand:
					ReceiveCommand_Player_id0_UnityEngine__char_46_Animator__char_46_SetTrigger_d210a4b9_ddf7_480f_9743_18bf1cd06aa8(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncPlayer_id0] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
