// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_20d53524fceab40d5a9ab892525615cb_d34657af8900466f81ebcda7b52c281f : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_20d53524fceab40d5a9ab892525615cb_64c2e2c02f7f4ed9a1c5d5ce2b9ca101 : IntBinding
    {   
        private global::Coherence.FirstSteps.Counter CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.FirstSteps.Counter)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_20d53524fceab40d5a9ab892525615cb_5847726189716557621);
        public override string CoherenceComponentName => "_20d53524fceab40d5a9ab892525615cb_5847726189716557621";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.count); }
            set { CastedUnityComponent.count = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_20d53524fceab40d5a9ab892525615cb_5847726189716557621)coherenceComponent).count;

            var simFrame = ((_20d53524fceab40d5a9ab892525615cb_5847726189716557621)coherenceComponent).countSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_20d53524fceab40d5a9ab892525615cb_5847726189716557621)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.count = Value;
            }
            else
            {
                update.count = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.countSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _20d53524fceab40d5a9ab892525615cb_5847726189716557621();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_20d53524fceab40d5a9ab892525615cb : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_20d53524fceab40d5a9ab892525615cb>();
        
        private global::Coherence.FirstSteps.Counter _20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814_CommandTarget;
        private global::Coherence.FirstSteps.Counter _20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["d34657af8900466f81ebcda7b52c281f"] = new Binding_20d53524fceab40d5a9ab892525615cb_d34657af8900466f81ebcda7b52c281f(),
			["64c2e2c02f7f4ed9a1c5d5ce2b9ca101"] = new Binding_20d53524fceab40d5a9ab892525615cb_64c2e2c02f7f4ed9a1c5d5ce2b9ca101(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_20d53524fceab40d5a9ab892525615cb()
        {
            bakedCommandBindings.Add("51bbdff1d75844e38e05ad8d40305814", BakeCommandBinding__20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814);
            bakedCommandBindings.Add("cec10b75335d48519f4b958f85ca6685", BakeCommandBinding__20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814_CommandTarget = (global::Coherence.FirstSteps.Counter)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Coherence.FirstSteps.Counter.AddOne",
            	"()",
            	SendCommand__20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814,
            	ReceiveLocalCommand__20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814,
            	MessageTarget.All,
            	_20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814(GenericCommandRequestArgs requestArgs)
        {
            var command = new _20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814(GenericCommandRequestArgs requestArgs)
        {
            var command = new _20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814(command);
        }

        private void ReceiveCommand__20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814(_20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814 command)
        {
            var target = _20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814_CommandTarget;
			target.AddOne();
        }
        private void BakeCommandBinding__20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685_CommandTarget = (global::Coherence.FirstSteps.Counter)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Coherence.FirstSteps.Counter.ResetToZero",
            	"()",
            	SendCommand__20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685,
            	ReceiveLocalCommand__20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685,
            	MessageTarget.All,
            	_20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685(GenericCommandRequestArgs requestArgs)
        {
            var command = new _20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685(GenericCommandRequestArgs requestArgs)
        {
            var command = new _20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685(command);
        }

        private void ReceiveCommand__20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685(_20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685 command)
        {
            var target = _20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685_CommandTarget;
			target.ResetToZero();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814 castedCommand:
                    ReceiveCommand__20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814(castedCommand);
                    break;
                case _20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685 castedCommand:
                    ReceiveCommand__20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_20d53524fceab40d5a9ab892525615cb Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_20d53524fceab40d5a9ab892525615cb>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
