// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>

namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;

    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_20d53524fceab40d5a9ab892525615cb_d34657af8900466f81ebcda7b52c281f : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override uint CoherenceComponentID => 0;
        public override int FieldIndex => 0;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetVector3().ToUnityVector3();
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = field.GetSimFrame();
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetVector3(Value.ToVector3d());
            }
            else
            {
                field.SetVector3(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond).ToVector3d());
            }

            field.SetSimFrame(simFrame);
        } 
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_20d53524fceab40d5a9ab892525615cb_64c2e2c02f7f4ed9a1c5d5ce2b9ca101 : IntBinding
    {   
        private global::Coherence.FirstSteps.Counter CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Coherence.FirstSteps.Counter)UnityComponent;
        }

        public override uint CoherenceComponentID => 18;
        public override int FieldIndex => 0;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.count); }
            set { CastedUnityComponent.count = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var field = coherenceComponent.GetField(0);
            
            var value = field.GetInt();

            var simFrame = (AbsoluteSimulationFrame)0;
            
            return (value, simFrame);
        }

        public override void WriteComponentData(ComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var field = coherenceComponent.GetField(0);

            if (Interpolator.IsInterpolationNone || SyncMode == SyncMode.Manual)
            {
                field.SetInt(Value);
            }
            else
            {
                field.SetInt(GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond));
            }

        } 
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_20d53524fceab40d5a9ab892525615cb : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_20d53524fceab40d5a9ab892525615cb>();
        
        private global::Coherence.FirstSteps.Counter _20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516_CommandTarget;
        private global::Coherence.FirstSteps.Counter _20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["d34657af8900466f81ebcda7b52c281f"] = new Binding_20d53524fceab40d5a9ab892525615cb_d34657af8900466f81ebcda7b52c281f(),
			["64c2e2c02f7f4ed9a1c5d5ce2b9ca101"] = new Binding_20d53524fceab40d5a9ab892525615cb_64c2e2c02f7f4ed9a1c5d5ce2b9ca101(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_20d53524fceab40d5a9ab892525615cb()
        {
            bakedCommandBindings.Add("962216c5a5864efa8283fe5e3fd45516", BakeCommandBinding__20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516);
            bakedCommandBindings.Add("c40a4c55da31475f82beea7c43d06dc4", BakeCommandBinding__20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516_CommandTarget = (global::Coherence.FirstSteps.Counter)commandBinding.UnityComponent;
            var _20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516_localTarget = (global::Coherence.FirstSteps.Counter)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Coherence.FirstSteps.Counter.ResetToZero",
            	"()",
            	SendCommand__20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516,
            	__args => ReceiveLocalCommand__20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516(__args, _20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516_localTarget),
            	MessageTarget.All,
            	_20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(6, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516(GenericCommandRequestArgs requestArgs, global::Coherence.FirstSteps.Counter target)
        {
			target.ResetToZero();
        }

        private void ReceiveCommand__20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516(CommandData command)
        {
			var target = _20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516_CommandTarget;


            command.Dispose();

			target.ResetToZero();
        }
        private void BakeCommandBinding__20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4_CommandTarget = (global::Coherence.FirstSteps.Counter)commandBinding.UnityComponent;
            var _20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4_localTarget = (global::Coherence.FirstSteps.Counter)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
				"Coherence.FirstSteps.Counter.AddOne",
            	"()",
            	SendCommand__20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4,
            	__args => ReceiveLocalCommand__20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4(__args, _20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4_localTarget),
            	MessageTarget.All,
            	_20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4_localTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4(GenericCommandRequestArgs requestArgs)
        {
            var command = client.SchemaDataFactory.CreateCommand(7, entityId, requestArgs.Target, 
                requestArgs.UsesMeta, requestArgs.Sender, requestArgs.Frame);


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4(GenericCommandRequestArgs requestArgs, global::Coherence.FirstSteps.Counter target)
        {
			target.AddOne();
        }

        private void ReceiveCommand__20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4(CommandData command)
        {
			var target = _20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4_CommandTarget;


            command.Dispose();

			target.AddOne();
        }
        
        public override void ReceiveCommand(CommandData command)
        {
            switch (command.CommandID)
            {
                case 6:
                    ReceiveCommand__20d53524fceab40d5a9ab892525615cb_962216c5a5864efa8283fe5e3fd45516(command);
                    break;
                case 7:
                    ReceiveCommand__20d53524fceab40d5a9ab892525615cb_c40a4c55da31475f82beea7c43d06dc4(command);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_20d53524fceab40d5a9ab892525615cb Unhandled command: {command.CommandID}.");
                    break;
            }
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_20d53524fceab40d5a9ab892525615cb>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }

}
