// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    
    public struct Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410 : ICoherenceComponentData
    {
        public static uint pathMask => 0b00000000000000000000000000000001;
        public System.String path;
        public static uint pathDirtyCounterMask => 0b00000000000000000000000000000010;
        public System.Int32 pathDirtyCounter;
        
        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 153;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000011;
        public bool HasFields() => true;
        public bool HasRefFields() => false;
        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;  
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;   
        }
        
        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;
        public AbsoluteSimulationFrame Frame;
        
        private static readonly System.Int32 _pathDirtyCounter_Min = -1;
        private static readonly System.Int32 _pathDirtyCounter_Max = 2000;
    
        public void SetSimulationFrame(AbsoluteSimulationFrame frame)
        {
            Frame = frame;
        }
        
        public AbsoluteSimulationFrame GetSimulationFrame() => Frame;
        
        public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
        {
            var other = (Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410)data;

            FieldsMask |= mask;
            StoppedMask &= ~(mask);

            if ((mask & 0x01) != 0)
            {
                Frame = other.Frame;
                path = other.path;
            }
            
            mask >>= 1;
            if ((mask & 0x01) != 0)
            {
                Frame = other.Frame;
                pathDirtyCounter = other.pathDirtyCounter;
            }
            
            mask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }
        
        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }
        
        public static uint Serialize(Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410 data, uint mask, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 2);
            }

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
            
                var fieldValue = data.path;
            

            
                bitStream.WriteShortString(fieldValue);
            }
            
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.pathDirtyCounter, _pathDirtyCounter_Min, _pathDirtyCounter_Max, "Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410.pathDirtyCounter", logger);
                
                data.pathDirtyCounter = Coherence.Utils.Bounds.Clamp(data.pathDirtyCounter, _pathDirtyCounter_Min, _pathDirtyCounter_Max);
            
                var fieldValue = data.pathDirtyCounter;
            

            
                bitStream.WriteIntegerRange(fieldValue, 11, -1);
            }
            
            mask >>= 1;
          
            return mask;
        }
        
        public static (Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410, uint) Deserialize(InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(2);
            }

            var mask = (uint)0;
            var val = new Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410();
            if (bitStream.ReadMask())
            {
                val.path = bitStream.ReadShortString();
                mask |= pathMask;
            }
            if (bitStream.ReadMask())
            {
                val.pathDirtyCounter = bitStream.ReadIntegerRange(11, -1);
                mask |= pathDirtyCounterMask;
            }
                    
            val.FieldsMask = mask;
            val.StoppedMask = stoppedMask;

            return (val, mask);
        }
        
        public static (Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410, uint) DeserializeArchetypeCrate_27f1ac5097d4ee4409fbb87ad14f76c2_Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410_LOD0(InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(2);
            }

            var mask = (uint)0;
            var val = new Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410();
            if (bitStream.ReadMask())
            {
                val.path = bitStream.ReadShortString();
                mask |= pathMask;
            }
            if (bitStream.ReadMask())
            {
                val.pathDirtyCounter = bitStream.ReadIntegerRange(11, -1);
                mask |= pathDirtyCounterMask;
            }
                        
            val.FieldsMask = mask;
            val.StoppedMask = mask;
            
            return (val, mask);
        }
        
        public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
        {
            var last = lastSent as Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410?;
            
        }

        public override string ToString()
        {
            return $"Crate_27f1ac5097d4ee4409fbb87ad14f76c2_CoherenceNode_4939570989761225410(path: { path }, pathDirtyCounter: { pathDirtyCounter }, Mask: {System.Convert.ToString(FieldsMask, 2).PadLeft(2, '0')}), Stopped: {System.Convert.ToString(StoppedMask, 2).PadLeft(2, '0')})";
        }
    }
    

}