// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Connection;
    using Coherence.Entities;
    using Coherence.Serializer;
    using Coherence.Log;
    using Coherence.SimulationFrame;


    [UnityEngine.Scripting.Preserve]

    public class Definition : IDefinition
    {
        public const string schemaId = "e1db5f09aec2a463f8179e7076b68999158a07f2";
        public const uint InternalWorldPosition = 0;
        public const uint InternalWorldOrientation = 1;
        public const uint InternalLocalUserComponent = 2;
        public const uint InternalWorldPositionQuery = 3;
        public const uint InternalArchetypeComponent = 4;
        public const uint InternalPersistence = 5;
        public const uint InternalConnectedEntity = 6;
        public const uint InternalUniqueID = 7;
        public const uint InternalConnection = 8;
        public const uint InternalConnectionScene = 9;
        public const uint InternalGlobal = 10;
        public const uint InternalGlobalQuery = 11;
        public const uint InternalTag = 12;
        public const uint InternalTagQuery = 13;
        public const uint InternalPreserveChildren = 14;
        public const uint InternalScene = 15;
        public const uint InternalAssetId = 16;
        public const uint InternalGenericScale = 17;
        public const uint Internal_20d53524fceab40d5a9ab892525615cb_5847726189716557621 = 18;
        public const uint Internal_27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410 = 19;
        public const uint Internal_27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121 = 20;
        public const uint Internal_6ba8b7030c4bf544396f864fc9dd99de_107609493621447933 = 21;
        public const uint Internal_a0e6252c4d09f4fb28257804194356b6_5156161361901559470 = 22;
        public const uint Internal_a167402e36850884aa7ce3d374cd6c77_6689584802229134021 = 23;
        public const uint Internal_aa7ea8e0044f0964eb9c782a689ca1b1_3110171900669979710 = 24;
        public const uint Internal_aa7ea8e0044f0964eb9c782a689ca1b1_4231088705669423063 = 25;
        public const uint Internal_aa7ea8e0044f0964eb9c782a689ca1b1_511851952794508008 = 26;
        public const uint Internal_aa7ea8e0044f0964eb9c782a689ca1b1_6045207018197627436 = 27;
        public const uint Internal_aa7ea8e0044f0964eb9c782a689ca1b1_7591837871254792591 = 28;
        public const uint Internal_aa7ea8e0044f0964eb9c782a689ca1b1_9849676 = 29;
        public const uint Internal_ba50eecfd968a47c38959f27b05771b6_5459872012036489579 = 30;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066 = 31;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177 = 32;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199 = 33;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033 = 34;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941 = 35;
        public const uint InternalArchetype_20d53524fceab40d5a9ab892525615cb_WorldPosition_LOD0 = 36;
        public const uint InternalArchetype_20d53524fceab40d5a9ab892525615cb__20d53524fceab40d5a9ab892525615cb_5847726189716557621_LOD0 = 37;
        public const uint InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldPosition_LOD0 = 38;
        public const uint InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldOrientation_LOD0 = 39;
        public const uint InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_GenericScale_LOD0 = 40;
        public const uint InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121_LOD0 = 41;
        public const uint InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410_LOD0 = 42;
        public const uint InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldPosition_LOD0 = 43;
        public const uint InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldOrientation_LOD0 = 44;
        public const uint InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de__6ba8b7030c4bf544396f864fc9dd99de_107609493621447933_LOD0 = 45;
        public const uint InternalArchetype_a0e6252c4d09f4fb28257804194356b6_WorldPosition_LOD0 = 46;
        public const uint InternalArchetype_a0e6252c4d09f4fb28257804194356b6_WorldOrientation_LOD0 = 47;
        public const uint InternalArchetype_a0e6252c4d09f4fb28257804194356b6_GenericScale_LOD0 = 48;
        public const uint InternalArchetype_a0e6252c4d09f4fb28257804194356b6__a0e6252c4d09f4fb28257804194356b6_5156161361901559470_LOD0 = 49;
        public const uint InternalArchetype_a167402e36850884aa7ce3d374cd6c77_WorldPosition_LOD0 = 50;
        public const uint InternalArchetype_a167402e36850884aa7ce3d374cd6c77_WorldOrientation_LOD0 = 51;
        public const uint InternalArchetype_a167402e36850884aa7ce3d374cd6c77_GenericScale_LOD0 = 52;
        public const uint InternalArchetype_a167402e36850884aa7ce3d374cd6c77__a167402e36850884aa7ce3d374cd6c77_6689584802229134021_LOD0 = 53;
        public const uint InternalArchetype_ba50eecfd968a47c38959f27b05771b6_WorldPosition_LOD0 = 54;
        public const uint InternalArchetype_ba50eecfd968a47c38959f27b05771b6__ba50eecfd968a47c38959f27b05771b6_5459872012036489579_LOD0 = 55;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldPosition_LOD0 = 56;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldOrientation_LOD0 = 57;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_GenericScale_LOD0 = 58;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177_LOD0 = 59;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199_LOD0 = 60;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066_LOD0 = 61;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941_LOD0 = 62;
        public const uint InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033_LOD0 = 63;
        public const uint InternalAuthorityRequest = 0;
        public const uint InternalAuthorityTransfer = 1;
        public const uint InternalQuerySynced = 2;
        public const uint InternalAdoptOrphan = 3;
        public const uint InternalPersistenceReady = 4;
        public const uint InternalSceneIndexChanged = 5;
        public const uint Internal_20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814 = 6;
        public const uint Internal_20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685 = 7;
        public const uint Internal_aa7ea8e0044f0964eb9c782a689ca1b1_d935ef02354c46c2bdb5dc4086cefeb7 = 8;
        public const uint Internal_cd9bcc1feead9419fac0c5981ce85c23_d210a4b9ddf7480f974318bf1cd06aa8 = 9;

        private static readonly Dictionary<uint, string> componentNamesForTypeIds = new Dictionary<uint, string>()
        {
            { 0, "WorldPosition" },
            { 1, "WorldOrientation" },
            { 2, "LocalUserComponent" },
            { 3, "WorldPositionQuery" },
            { 4, "ArchetypeComponent" },
            { 5, "Persistence" },
            { 6, "ConnectedEntity" },
            { 7, "UniqueID" },
            { 8, "Connection" },
            { 9, "ConnectionScene" },
            { 10, "Global" },
            { 11, "GlobalQuery" },
            { 12, "Tag" },
            { 13, "TagQuery" },
            { 14, "PreserveChildren" },
            { 15, "Scene" },
            { 16, "AssetId" },
            { 17, "GenericScale" },
            { 18, "_20d53524fceab40d5a9ab892525615cb_5847726189716557621" },
            { 19, "_27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410" },
            { 20, "_27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121" },
            { 21, "_6ba8b7030c4bf544396f864fc9dd99de_107609493621447933" },
            { 22, "_a0e6252c4d09f4fb28257804194356b6_5156161361901559470" },
            { 23, "_a167402e36850884aa7ce3d374cd6c77_6689584802229134021" },
            { 24, "_aa7ea8e0044f0964eb9c782a689ca1b1_3110171900669979710" },
            { 25, "_aa7ea8e0044f0964eb9c782a689ca1b1_4231088705669423063" },
            { 26, "_aa7ea8e0044f0964eb9c782a689ca1b1_511851952794508008" },
            { 27, "_aa7ea8e0044f0964eb9c782a689ca1b1_6045207018197627436" },
            { 28, "_aa7ea8e0044f0964eb9c782a689ca1b1_7591837871254792591" },
            { 29, "_aa7ea8e0044f0964eb9c782a689ca1b1_9849676" },
            { 30, "_ba50eecfd968a47c38959f27b05771b6_5459872012036489579" },
            { 31, "_cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066" },
            { 32, "_cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177" },
            { 33, "_cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199" },
            { 34, "_cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033" },
            { 35, "_cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941" },
            { 36, "Archetype_20d53524fceab40d5a9ab892525615cb_WorldPosition_LOD0" },
            { 37, "Archetype_20d53524fceab40d5a9ab892525615cb__20d53524fceab40d5a9ab892525615cb_5847726189716557621_LOD0" },
            { 38, "Archetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldPosition_LOD0" },
            { 39, "Archetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldOrientation_LOD0" },
            { 40, "Archetype_27f1ac5097d4ee4409fbb87ad14f76c2_GenericScale_LOD0" },
            { 41, "Archetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121_LOD0" },
            { 42, "Archetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410_LOD0" },
            { 43, "Archetype_6ba8b7030c4bf544396f864fc9dd99de_WorldPosition_LOD0" },
            { 44, "Archetype_6ba8b7030c4bf544396f864fc9dd99de_WorldOrientation_LOD0" },
            { 45, "Archetype_6ba8b7030c4bf544396f864fc9dd99de__6ba8b7030c4bf544396f864fc9dd99de_107609493621447933_LOD0" },
            { 46, "Archetype_a0e6252c4d09f4fb28257804194356b6_WorldPosition_LOD0" },
            { 47, "Archetype_a0e6252c4d09f4fb28257804194356b6_WorldOrientation_LOD0" },
            { 48, "Archetype_a0e6252c4d09f4fb28257804194356b6_GenericScale_LOD0" },
            { 49, "Archetype_a0e6252c4d09f4fb28257804194356b6__a0e6252c4d09f4fb28257804194356b6_5156161361901559470_LOD0" },
            { 50, "Archetype_a167402e36850884aa7ce3d374cd6c77_WorldPosition_LOD0" },
            { 51, "Archetype_a167402e36850884aa7ce3d374cd6c77_WorldOrientation_LOD0" },
            { 52, "Archetype_a167402e36850884aa7ce3d374cd6c77_GenericScale_LOD0" },
            { 53, "Archetype_a167402e36850884aa7ce3d374cd6c77__a167402e36850884aa7ce3d374cd6c77_6689584802229134021_LOD0" },
            { 54, "Archetype_ba50eecfd968a47c38959f27b05771b6_WorldPosition_LOD0" },
            { 55, "Archetype_ba50eecfd968a47c38959f27b05771b6__ba50eecfd968a47c38959f27b05771b6_5459872012036489579_LOD0" },
            { 56, "Archetype_cd9bcc1feead9419fac0c5981ce85c23_WorldPosition_LOD0" },
            { 57, "Archetype_cd9bcc1feead9419fac0c5981ce85c23_WorldOrientation_LOD0" },
            { 58, "Archetype_cd9bcc1feead9419fac0c5981ce85c23_GenericScale_LOD0" },
            { 59, "Archetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177_LOD0" },
            { 60, "Archetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199_LOD0" },
            { 61, "Archetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066_LOD0" },
            { 62, "Archetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941_LOD0" },
            { 63, "Archetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033_LOD0" },
        };

        public static string ComponentNameForTypeId(uint typeId)
        {
            if (componentNamesForTypeIds.TryGetValue(typeId, out string componentName))
            {
                return componentName;
            }
            else
            {
                return "";
            }
        }

        public static readonly Dictionary<uint, MessageTarget> CommandRoutingByType = new Dictionary<uint, MessageTarget>()
        {
            { Definition.InternalAuthorityRequest , MessageTarget.All },
            { Definition.InternalAuthorityTransfer , MessageTarget.All },
            { Definition.InternalQuerySynced , MessageTarget.All },
            { Definition.InternalAdoptOrphan , MessageTarget.All },
            { Definition.InternalPersistenceReady , MessageTarget.All },
            { Definition.InternalSceneIndexChanged , MessageTarget.All },
            { Definition.Internal_20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814 , MessageTarget.All },
            { Definition.Internal_20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685 , MessageTarget.All },
            { Definition.Internal_aa7ea8e0044f0964eb9c782a689ca1b1_d935ef02354c46c2bdb5dc4086cefeb7 , MessageTarget.All },
            { Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_d210a4b9ddf7480f974318bf1cd06aa8 , MessageTarget.All },
        };

        public ICoherenceComponentData ReadComponentUpdate(uint componentType, AbsoluteSimulationFrame referenceSimulationFrame,
            IInBitStream bitStream, Logger logger)
        {
            var inProtocolStream = new InProtocolBitStream(bitStream);

            switch (componentType)
            {
                case InternalWorldPosition:
                    return WorldPosition.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldOrientation:
                    return WorldOrientation.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPersistence:
                    return Persistence.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectedEntity:
                    return ConnectedEntity.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalUniqueID:
                    return UniqueID.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnection:
                    return Connection.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectionScene:
                    return ConnectionScene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobal:
                    return Global.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobalQuery:
                    return GlobalQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTag:
                    return Tag.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTagQuery:
                    return TagQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPreserveChildren:
                    return PreserveChildren.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalScene:
                    return Scene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalAssetId:
                    return AssetId.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGenericScale:
                    return GenericScale.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_20d53524fceab40d5a9ab892525615cb_5847726189716557621:
                    return _20d53524fceab40d5a9ab892525615cb_5847726189716557621.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_6ba8b7030c4bf544396f864fc9dd99de_107609493621447933:
                    return _6ba8b7030c4bf544396f864fc9dd99de_107609493621447933.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a0e6252c4d09f4fb28257804194356b6_5156161361901559470:
                    return _a0e6252c4d09f4fb28257804194356b6_5156161361901559470.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a167402e36850884aa7ce3d374cd6c77_6689584802229134021:
                    return _a167402e36850884aa7ce3d374cd6c77_6689584802229134021.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_3110171900669979710:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_3110171900669979710.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_4231088705669423063:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_4231088705669423063.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_511851952794508008:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_511851952794508008.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_6045207018197627436:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_6045207018197627436.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_7591837871254792591:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_7591837871254792591.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_9849676:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_9849676.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_ba50eecfd968a47c38959f27b05771b6_5459872012036489579:
                    return _ba50eecfd968a47c38959f27b05771b6_5459872012036489579.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066:
                    return _cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177:
                    return _cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199:
                    return _cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033:
                    return _cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941:
                    return _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_20d53524fceab40d5a9ab892525615cb_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_20d53524fceab40d5a9ab892525615cb_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_20d53524fceab40d5a9ab892525615cb__20d53524fceab40d5a9ab892525615cb_5847726189716557621_LOD0:
                    return _20d53524fceab40d5a9ab892525615cb_5847726189716557621.DeserializeArchetype_20d53524fceab40d5a9ab892525615cb__20d53524fceab40d5a9ab892525615cb_5847726189716557621_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldOrientation_LOD0:
                    return WorldOrientation.DeserializeArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldOrientation_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_GenericScale_LOD0:
                    return GenericScale.DeserializeArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_GenericScale_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121_LOD0:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121.DeserializeArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410_LOD0:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410.DeserializeArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldOrientation_LOD0:
                    return WorldOrientation.DeserializeArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldOrientation_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de__6ba8b7030c4bf544396f864fc9dd99de_107609493621447933_LOD0:
                    return _6ba8b7030c4bf544396f864fc9dd99de_107609493621447933.DeserializeArchetype_6ba8b7030c4bf544396f864fc9dd99de__6ba8b7030c4bf544396f864fc9dd99de_107609493621447933_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a0e6252c4d09f4fb28257804194356b6_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_a0e6252c4d09f4fb28257804194356b6_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a0e6252c4d09f4fb28257804194356b6_WorldOrientation_LOD0:
                    return WorldOrientation.DeserializeArchetype_a0e6252c4d09f4fb28257804194356b6_WorldOrientation_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a0e6252c4d09f4fb28257804194356b6_GenericScale_LOD0:
                    return GenericScale.DeserializeArchetype_a0e6252c4d09f4fb28257804194356b6_GenericScale_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a0e6252c4d09f4fb28257804194356b6__a0e6252c4d09f4fb28257804194356b6_5156161361901559470_LOD0:
                    return _a0e6252c4d09f4fb28257804194356b6_5156161361901559470.DeserializeArchetype_a0e6252c4d09f4fb28257804194356b6__a0e6252c4d09f4fb28257804194356b6_5156161361901559470_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a167402e36850884aa7ce3d374cd6c77_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_a167402e36850884aa7ce3d374cd6c77_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a167402e36850884aa7ce3d374cd6c77_WorldOrientation_LOD0:
                    return WorldOrientation.DeserializeArchetype_a167402e36850884aa7ce3d374cd6c77_WorldOrientation_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a167402e36850884aa7ce3d374cd6c77_GenericScale_LOD0:
                    return GenericScale.DeserializeArchetype_a167402e36850884aa7ce3d374cd6c77_GenericScale_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a167402e36850884aa7ce3d374cd6c77__a167402e36850884aa7ce3d374cd6c77_6689584802229134021_LOD0:
                    return _a167402e36850884aa7ce3d374cd6c77_6689584802229134021.DeserializeArchetype_a167402e36850884aa7ce3d374cd6c77__a167402e36850884aa7ce3d374cd6c77_6689584802229134021_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_ba50eecfd968a47c38959f27b05771b6_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_ba50eecfd968a47c38959f27b05771b6_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_ba50eecfd968a47c38959f27b05771b6__ba50eecfd968a47c38959f27b05771b6_5459872012036489579_LOD0:
                    return _ba50eecfd968a47c38959f27b05771b6_5459872012036489579.DeserializeArchetype_ba50eecfd968a47c38959f27b05771b6__ba50eecfd968a47c38959f27b05771b6_5459872012036489579_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldOrientation_LOD0:
                    return WorldOrientation.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23_WorldOrientation_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23_GenericScale_LOD0:
                    return GenericScale.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23_GenericScale_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177_LOD0:
                    return _cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199_LOD0:
                    return _cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066_LOD0:
                    return _cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941_LOD0:
                    return _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033_LOD0:
                    return _cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033.DeserializeArchetype_cd9bcc1feead9419fac0c5981ce85c23__cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033_LOD0(referenceSimulationFrame, inProtocolStream);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(componentType),
                        $"Missing serialization implementation for a component: {componentType}");
            }
        }

        public uint WriteComponentUpdate(ICoherenceComponentData data, uint serializeAs, bool isRefSimFrameValid,
            AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream protocolStream, Logger logger)
        {
            switch (serializeAs)
            {
                case InternalWorldPosition:
                    return WorldPosition.Serialize((WorldPosition)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldOrientation:
                    return WorldOrientation.Serialize((WorldOrientation)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Serialize((LocalUserComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Serialize((WorldPositionQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Serialize((ArchetypeComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPersistence:
                    return Persistence.Serialize((Persistence)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectedEntity:
                    return ConnectedEntity.Serialize((ConnectedEntity)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalUniqueID:
                    return UniqueID.Serialize((UniqueID)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnection:
                    return Connection.Serialize((Connection)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectionScene:
                    return ConnectionScene.Serialize((ConnectionScene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobal:
                    return Global.Serialize((Global)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobalQuery:
                    return GlobalQuery.Serialize((GlobalQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTag:
                    return Tag.Serialize((Tag)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTagQuery:
                    return TagQuery.Serialize((TagQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPreserveChildren:
                    return PreserveChildren.Serialize((PreserveChildren)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalScene:
                    return Scene.Serialize((Scene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalAssetId:
                    return AssetId.Serialize((AssetId)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGenericScale:
                    return GenericScale.Serialize((GenericScale)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_20d53524fceab40d5a9ab892525615cb_5847726189716557621:
                    return _20d53524fceab40d5a9ab892525615cb_5847726189716557621.Serialize((_20d53524fceab40d5a9ab892525615cb_5847726189716557621)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410.Serialize((_27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121.Serialize((_27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_6ba8b7030c4bf544396f864fc9dd99de_107609493621447933:
                    return _6ba8b7030c4bf544396f864fc9dd99de_107609493621447933.Serialize((_6ba8b7030c4bf544396f864fc9dd99de_107609493621447933)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a0e6252c4d09f4fb28257804194356b6_5156161361901559470:
                    return _a0e6252c4d09f4fb28257804194356b6_5156161361901559470.Serialize((_a0e6252c4d09f4fb28257804194356b6_5156161361901559470)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a167402e36850884aa7ce3d374cd6c77_6689584802229134021:
                    return _a167402e36850884aa7ce3d374cd6c77_6689584802229134021.Serialize((_a167402e36850884aa7ce3d374cd6c77_6689584802229134021)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_3110171900669979710:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_3110171900669979710.Serialize((_aa7ea8e0044f0964eb9c782a689ca1b1_3110171900669979710)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_4231088705669423063:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_4231088705669423063.Serialize((_aa7ea8e0044f0964eb9c782a689ca1b1_4231088705669423063)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_511851952794508008:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_511851952794508008.Serialize((_aa7ea8e0044f0964eb9c782a689ca1b1_511851952794508008)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_6045207018197627436:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_6045207018197627436.Serialize((_aa7ea8e0044f0964eb9c782a689ca1b1_6045207018197627436)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_7591837871254792591:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_7591837871254792591.Serialize((_aa7ea8e0044f0964eb9c782a689ca1b1_7591837871254792591)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_aa7ea8e0044f0964eb9c782a689ca1b1_9849676:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_9849676.Serialize((_aa7ea8e0044f0964eb9c782a689ca1b1_9849676)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_ba50eecfd968a47c38959f27b05771b6_5459872012036489579:
                    return _ba50eecfd968a47c38959f27b05771b6_5459872012036489579.Serialize((_ba50eecfd968a47c38959f27b05771b6_5459872012036489579)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066:
                    return _cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_2783100773886260066)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177:
                    return _cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_4582869309862079177)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199:
                    return _cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_5911091967807195199)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033:
                    return _cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_7791709351172572033)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941:
                    return _cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_8498588009909292941)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingComponentImplementation, ("component", data.GetComponentType()));
                    return 0;
            }
        }

        private IEntityCommand ReadCommand(uint commandType, Entity entity, MessageTarget target, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    return AuthorityRequest.Deserialize(bitStream, entity, target);
                case Definition.InternalAuthorityTransfer:
                    return AuthorityTransfer.Deserialize(bitStream, entity, target);
                case Definition.InternalQuerySynced:
                    return QuerySynced.Deserialize(bitStream, entity, target);
                case Definition.InternalAdoptOrphan:
                    return AdoptOrphan.Deserialize(bitStream, entity, target);
                case Definition.InternalPersistenceReady:
                    return PersistenceReady.Deserialize(bitStream, entity, target);
                case Definition.InternalSceneIndexChanged:
                    return SceneIndexChanged.Deserialize(bitStream, entity, target);
                case Definition.Internal_20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814:
                    return _20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814.Deserialize(bitStream, entity, target);
                case Definition.Internal_20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685:
                    return _20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685.Deserialize(bitStream, entity, target);
                case Definition.Internal_aa7ea8e0044f0964eb9c782a689ca1b1_d935ef02354c46c2bdb5dc4086cefeb7:
                    return _aa7ea8e0044f0964eb9c782a689ca1b1_d935ef02354c46c2bdb5dc4086cefeb7.Deserialize(bitStream, entity, target);
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_d210a4b9ddf7480f974318bf1cd06aa8:
                    return _cd9bcc1feead9419fac0c5981ce85c23_d210a4b9ddf7480f974318bf1cd06aa8.Deserialize(bitStream, entity, target);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(commandType),
                        $"Missing serialization implementation for a command: {commandType}");
            }
        }

        private IEntityInput ReadInput(uint inputType, Entity entity, long frame, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (inputType)
            {
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(inputType),
                        $"Missing serialization implementation for an input: {inputType}");
            }
        }

        public IEntityCommand[]	ReadCommands(IInBitStream bitStream, Logger logger)
        {
            var numMessages = bitStream.ReadUint8();

            var commandData = new IEntityCommand[numMessages];

            for (var i = 0; i < numMessages; i++)
            {
            	commandData[i] = ReadCommand(bitStream, logger);
            }

            return commandData;
        }

        public IEntityInput[] ReadInputs(IInBitStream bitStream, Logger logger)
        {
            var numMessages = bitStream.ReadUint8();

            var inputData = new IEntityInput[numMessages];

            for (var i = 0; i < numMessages; i++)
            {
                var entityID = DeserializerTools.DeserializeEntity(bitStream);
                var routing = DeserializerTools.DeserializeMessageTarget(bitStream);
                var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
                var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
                var frame = (long)bitStream.ReadUint64();
                var input = ReadInput(componentType, entityID, frame, inBitStream, logger);
                input.Routing = routing;
                inputData[i] = input;
            }

            return inputData;
        }

        public IEntityCommand ReadCommand(IInBitStream bitStream, Logger logger)
        {
            var entityID = DeserializerTools.DeserializeEntity(bitStream);
            var messageTarget = DeserializerTools.DeserializeMessageTarget(bitStream);
            var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
            var meta = DeserializerTools.DeserializeCommandMeta(bitStream);
            var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);

			var command = ReadCommand(componentType, entityID, messageTarget, inBitStream, logger);
			if (meta.HasValue)
			{
				command.UsesMeta = true;
				command.SenderClientID = new ClientID(meta.Value.SenderID);
				command.Frame = meta.Value.Frame;
			}

            return command;
        }

        public void WriteCommand(IEntityCommand data, uint commandType, IOutProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    AuthorityRequest.Serialize((AuthorityRequest)data, bitStream);
                    break;
                case Definition.InternalAuthorityTransfer:
                    AuthorityTransfer.Serialize((AuthorityTransfer)data, bitStream);
                    break;
                case Definition.InternalQuerySynced:
                    QuerySynced.Serialize((QuerySynced)data, bitStream);
                    break;
                case Definition.InternalAdoptOrphan:
                    AdoptOrphan.Serialize((AdoptOrphan)data, bitStream);
                    break;
                case Definition.InternalPersistenceReady:
                    PersistenceReady.Serialize((PersistenceReady)data, bitStream);
                    break;
                case Definition.InternalSceneIndexChanged:
                    SceneIndexChanged.Serialize((SceneIndexChanged)data, bitStream);
                    break;
                case Definition.Internal_20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814:
                    _20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814.Serialize((_20d53524fceab40d5a9ab892525615cb_51bbdff1d75844e38e05ad8d40305814)data, bitStream);
                    break;
                case Definition.Internal_20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685:
                    _20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685.Serialize((_20d53524fceab40d5a9ab892525615cb_cec10b75335d48519f4b958f85ca6685)data, bitStream);
                    break;
                case Definition.Internal_aa7ea8e0044f0964eb9c782a689ca1b1_d935ef02354c46c2bdb5dc4086cefeb7:
                    _aa7ea8e0044f0964eb9c782a689ca1b1_d935ef02354c46c2bdb5dc4086cefeb7.Serialize((_aa7ea8e0044f0964eb9c782a689ca1b1_d935ef02354c46c2bdb5dc4086cefeb7)data, bitStream);
                    break;
                case Definition.Internal_cd9bcc1feead9419fac0c5981ce85c23_d210a4b9ddf7480f974318bf1cd06aa8:
                    _cd9bcc1feead9419fac0c5981ce85c23_d210a4b9ddf7480f974318bf1cd06aa8.Serialize((_cd9bcc1feead9419fac0c5981ce85c23_d210a4b9ddf7480f974318bf1cd06aa8)data, bitStream);
                    break;
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingCommandImplementation, ("command", commandType));
                    break;
            }
        }

        public void WriteInput(IEntityInput data, uint inputType, IOutProtocolBitStream bitStream, Logger logger)
        {
            var inputData = (InputData)data;

            switch (inputType)
            {
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingInputImplementation, ("input", inputType));
                    break;
            }
        }

        public IEntityCommand CreateAuthorityRequest(Entity entity, ClientID requester, AuthorityType authType)
        {
            return new AuthorityRequest(entity, (uint)requester, (int)authType)
			{
				Target = MessageTarget.StateAuthorityOnly,
			};
        }

        public IEntityCommand CreateAdoptOrphanCommand(Entity entity)
        {
            return new AdoptOrphan
            {
                Entity = entity,
                Target = MessageTarget.StateAuthorityOnly,
            };
        }

        public bool TryGetAuthorityRequestCommand(IEntityCommand entityCommand,
            out ClientID requester, out AuthorityType authType)
        {
            if (entityCommand is AuthorityRequest request)
            {
                requester = (ClientID)request.requester;
                authType = (AuthorityType)request.authorityType;

                return true;
            }

            requester = default;
            authType = default;

            return false;
        }

        public IEntityCommand CreateAuthorityTransfer(Entity entity, ClientID newAuthority, bool accepted, AuthorityType authType)
        {
            return new AuthorityTransfer(entity, (uint)newAuthority, accepted, (int)authType)
			{
				Target = MessageTarget.Other,
			};
        }

        public bool TryGetAuthorityTransferCommand(IEntityCommand entityCommand, out ClientID newAuthority,
            out bool transferAccepted, out AuthorityType authType)
        {
            if (entityCommand is AuthorityTransfer transfer)
            {
                newAuthority = (ClientID)transfer.newAuthority;
                transferAccepted = transfer.accepted;
                authType = (AuthorityType)transfer.authorityType;

                return true;
            }

            newAuthority = default;
            transferAccepted = default;
            authType = default;

            return false;
        }

        public ICoherenceComponentData GeneratePersistenceData()
        {
            var persistence = new Persistence();

            return persistence;
        }

        public ICoherenceComponentData GenerateCoherenceUUIDData(string uuid, AbsoluteSimulationFrame simFrame)
        {
            var uniqueID = new UniqueID();
            uniqueID.uuid = uuid;
            uniqueID.uuidSimulationFrame = simFrame;
            uniqueID.FieldsMask = 0b1;

            return uniqueID;
        }

        public ICoherenceComponentData CreateGlobalComponent()
        {
            return new Global();
        }

        public ICoherenceComponentData GenerateGlobalQueryComponent()
        {
            return new GlobalQuery();
        }

        public string ExtractCoherenceUUID(ICoherenceComponentData data)
        {
            var uniqueID = (UniqueID)data;
            return uniqueID.uuid;
        }

        public bool IsConnectedEntity(ICoherenceComponentData data)
        {
            return data.GetComponentType() == Definition.InternalConnectedEntity;
        }

        public Entity ExtractConnectedEntityID(ICoherenceComponentData data)
        {
            var connectedEntity = (ConnectedEntity)data;

            return connectedEntity.value;
        }

        public string ExtractCoherenceTag(ICoherenceComponentData data)
        {
            var tag = (Tag)data;
            return tag.tag;
        }

        public bool TryGetSceneIndexChangedCommand(IEntityCommand entityCommand, out int sceneIndex)
        {
            if (entityCommand is SceneIndexChanged changed)
            {
                sceneIndex = (int)changed.sceneIndex;

                return true;
            }

            sceneIndex = default;

            return false;
        }

        public IEntityCommand CreateSceneIndexChangedCommand(Entity entity, int sceneIndex)
        {
            return new SceneIndexChanged(entity, sceneIndex)
			{
				Target = MessageTarget.StateAuthorityOnly,
			};
        }

        public bool IsSendOrderedComponent(uint componentID)
        {
            switch(componentID)
            {
                case 6:
                    return true;
                default:
                    return false;
            }
        }
}


}
