// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    
    public struct Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021 : ICoherenceComponentData
    {
        public static uint timePlantedMask => 0b00000000000000000000000000000001;
        public System.UInt32 timePlanted;
        
        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 156;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000001;
        public bool HasFields() => true;
        public bool HasRefFields() => false;
        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;  
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;   
        }
        
        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;
        public AbsoluteSimulationFrame Frame;
        
        private static readonly System.UInt32 _timePlanted_Min = 0;
        private static readonly System.UInt32 _timePlanted_Max = 4294967295;
    
        public void SetSimulationFrame(AbsoluteSimulationFrame frame)
        {
            Frame = frame;
        }
        
        public AbsoluteSimulationFrame GetSimulationFrame() => Frame;
        
        public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
        {
            var other = (Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021)data;

            FieldsMask |= mask;
            StoppedMask &= ~(mask);

            if ((mask & 0x01) != 0)
            {
                Frame = other.Frame;
                timePlanted = other.timePlanted;
            }
            
            mask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }
        
        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }
        
        public static uint Serialize(Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021 data, uint mask, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 1);
            }

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                Coherence.Utils.Bounds.Check(data.timePlanted, _timePlanted_Min, _timePlanted_Max, "Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021.timePlanted", logger);
                
                data.timePlanted = Coherence.Utils.Bounds.Clamp(data.timePlanted, _timePlanted_Min, _timePlanted_Max);
            
                var fieldValue = data.timePlanted;
            

            
                bitStream.WriteUIntegerRange(fieldValue, 32, 0);
            }
            
            mask >>= 1;
          
            return mask;
        }
        
        public static (Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021, uint) Deserialize(InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(1);
            }

            var mask = (uint)0;
            var val = new Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021();
            if (bitStream.ReadMask())
            {
                val.timePlanted = bitStream.ReadUIntegerRange(32, 0);
                mask |= timePlantedMask;
            }
                    
            val.FieldsMask = mask;
            val.StoppedMask = stoppedMask;

            return (val, mask);
        }
        
        public static (Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021, uint) DeserializeArchetypeFlower_a167402e36850884aa7ce3d374cd6c77_Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021_LOD0(InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(1);
            }

            var mask = (uint)0;
            var val = new Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021();
            if (bitStream.ReadMask())
            {
                val.timePlanted = bitStream.ReadUIntegerRange(32, 0);
                mask |= timePlantedMask;
            }
                        
            val.FieldsMask = mask;
            val.StoppedMask = mask;
            
            return (val, mask);
        }
        
        public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
        {
            var last = lastSent as Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021?;
            
        }

        public override string ToString()
        {
            return $"Flower_a167402e36850884aa7ce3d374cd6c77_Flower_6689584802229134021(timePlanted: { timePlanted }, Mask: {System.Convert.ToString(FieldsMask, 2).PadLeft(1, '0')}), Stopped: {System.Convert.ToString(StoppedMask, 2).PadLeft(1, '0')})";
        }
    }
    

}