// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using System.Collections.Generic;
    using UnityEngine;

    public struct FlowersCounter_20d53524fceab40d5a9ab892525615cb_20d53524fceab40d5a9ab892525615cb_2f75e994_88a8_4da2_aebe_765c3648d9d8 : IEntityCommand
    {
        
        public Entity Entity { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 6;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        
        public static void Serialize(FlowersCounter_20d53524fceab40d5a9ab892525615cb_20d53524fceab40d5a9ab892525615cb_2f75e994_88a8_4da2_aebe_765c3648d9d8 commandData, IOutProtocolBitStream bitStream)
        {
        }
        
        public static FlowersCounter_20d53524fceab40d5a9ab892525615cb_20d53524fceab40d5a9ab892525615cb_2f75e994_88a8_4da2_aebe_765c3648d9d8 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
    
            return new FlowersCounter_20d53524fceab40d5a9ab892525615cb_20d53524fceab40d5a9ab892525615cb_2f75e994_88a8_4da2_aebe_765c3648d9d8()
            {
                Entity = entity,
                Routing = target,
            };   
        }
    }

}