// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941 : ICoherenceComponentData
	{
		public float MoveSpeed;
		public bool Grounded;
		public bool CarryingBig;
		public bool CarryingSmall;

		public override string ToString()
		{
			return $"Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941(MoveSpeed: {MoveSpeed}, Grounded: {Grounded}, CarryingBig: {CarryingBig}, CarryingSmall: {CarryingSmall})";
		}

		public uint GetComponentType() => Definition.InternalPlayer_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941;

		public const int order = 0;

		public uint FieldsMask => 0b00000000000000000000000000001111;

		public int GetComponentOrder() => order;
		public bool IsSendOrdered() { return false; }

		public AbsoluteSimulationFrame Frame;
	
		private static readonly float _MoveSpeed_Min = 0f;
		private static readonly float _MoveSpeed_Max = 10f;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				MoveSpeed = other.MoveSpeed;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				Grounded = other.Grounded;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				CarryingBig = other.CarryingBig;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				CarryingSmall = other.CarryingSmall;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static uint Serialize(Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.MoveSpeed, _MoveSpeed_Min, _MoveSpeed_Max, "Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941.MoveSpeed");
				var fieldValue = data.MoveSpeed;

				bitStream.WriteFloat(fieldValue, FloatMeta.ForFixedPoint(0, 10, 0.001d));
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				var fieldValue = data.Grounded;

				bitStream.WriteBool(fieldValue);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				var fieldValue = data.CarryingBig;

				bitStream.WriteBool(fieldValue);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				var fieldValue = data.CarryingSmall;

				bitStream.WriteBool(fieldValue);
			}
			mask >>= 1;

			return mask;
		}

		public static (Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941, uint) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941();
	
			if (bitStream.ReadMask())
			{
				val.MoveSpeed = bitStream.ReadFloat(FloatMeta.ForFixedPoint(0, 10, 0.001d));
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.Grounded = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.CarryingBig = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.CarryingSmall = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000001000;
			}
			return (val, mask);
		}
		public static (Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941, uint) DeserializeArchetypePlayer_cd9bcc1feead9419fac0c5981ce85c23_Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941();
			if (bitStream.ReadMask())
			{
				val.MoveSpeed = bitStream.ReadFloat(FloatMeta.ForFixedPoint(0, 10, 0.001d));
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.Grounded = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.CarryingBig = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.CarryingSmall = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000001000;
			}

			return (val, mask);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Player_cd9bcc1feead9419fac0c5981ce85c23_UnityEngine__char_46_Animator_8498588009909292941?;
	
		}
	}
}